apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-db-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-db
  template:
    metadata:
      labels:
        app: todo-app-db
    spec:
      containers:
        - name: todo-app-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: app-secret
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: marciogabriel1998/todo-project:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secret
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
            terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-db-service
  namespace: default
spec:
  selector:
    app: todo-app-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: default
spec:
  selector:
    app: todo-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
          
